# Problem Set 2 - Angela Shoulders

## ACME Standard Library

### Problem 1

In [ ]:
L = [1,2,3]
print(min(L), max(L), sum(L)/len(L))

### Problem 2

In [ ]:
ex_int=1

In [ ]:
new_int=ex_int

In [ ]:
new_int += 1

In [ ]:
print(ex_int)
print(new_int)

In [ ]:
# so int is immutable

In [ ]:
ex_str="Angela"

In [ ]:
new_str=ex_str

In [ ]:
new_str += " Shoulders"

In [ ]:
print(ex_str)
print(new_str)

In [ ]:
# so str is immutable

In [ ]:
ex_list=[1,2,3]

In [ ]:
new_list=ex_list

In [ ]:
new_list += "100"

In [ ]:
print(ex_list)
print(new_list)

In [ ]:
# so list is mutable

In [ ]:
ex_tuple=(4,5,6)

In [ ]:
new_tuple=ex_tuple

In [ ]:
new_tuple += (1,)

In [ ]:
ex_tuple==new_tuple

In [ ]:
# so tuple is immutable

In [ ]:
ex_set={7,8,9}

In [ ]:
new_set=ex_set

In [ ]:
new_set.add(7)

In [ ]:
ex_set==new_set

In [ ]:
# so sets are mutable

### Problem 3

In [1]:
run ps2module.py

In [2]:
import ps2module as ps2

In [5]:
ps2.multiply(3,4)

12

In [8]:
def my_function(side1, side2):
    hypotenuse = sqrt(side1**2 + side2**2)
    return hypotenuse

my_function(2,2)

2.8284271247461903

## ACME Numpy Intro

In [1]:
import numpy as np

### Problem 1

In [4]:
A = np.array([[3,-1,4], [1,5,-9]])
B = np.array([[2,6,-5,3], [5,-8,9,7],[9,-3,-2,-3]])
def matrixmultiply(m1, m2):
    product = np.dot(m1, m2)
    return product

matrixmultiply(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

### Problem 2

In [6]:
A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
def function(matrix):
    result = -(matrix*matrix*matrix) + (9*matrix*matrix) - (15*matrix)
    return result

function(A)

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

### Problem 5

In [33]:
A = np.array([[0,2,4],[1,3,5]])
B = np.array([[3,0,0],[3,3,0],[3,3,3]])
C = np.array([[-2,0,0],[0,-2,0],[0,0,-2]])

group1 = np.vstack((np.zeros((4,3)),A,B))
group2 = np.vstack((A.T,np.zeros((3,2)),np.zeros((3,2))))
group3 = np.vstack((np.eye((3)),np.zeros((3,3)),C))
                   
np.hstack((group1,group2,group3))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

## ACME Object Oriented

### Problem 1

### Problem 2